import { StyleSheet } from 'react-native';
import { fontFamily } from '../../constants/fonts';
import colors from '../../constants/colors';

const styles = StyleSheet.create({
  boxShadow: {
    backgroundColor: '#ffffff',
    marginBottom: 12,
    marginLeft: 7,
    marginRight: 3,
    marginTop: 5,
    shadowColor: '#000000',
    shadowOffset: { height: 3, width: 0 },
    shadowOpacity: 0.16,
    shadowRadius: 6,
  },
  categoryButton: {
    padding: 6,
    paddingLeft: 20,
    paddingRight: 20,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#ffffff',
    marginRight: 5,
    marginBottom: 5,
  },
  categoryButtonActive: {
    padding: 6,
    paddingLeft: 20,
    paddingRight: 20,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#ffffff',
    backgroundColor: '#ffffff',
    marginRight: 5,
    marginBottom: 5,
  },
  categorySubmitButton: {
    padding: 8,
    paddingLeft: 20,
    paddingRight: 20,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#ffffff',
    backgroundColor: '#ffffff',
    marginTop: 0,
    marginBottom: 0,
    width: 125,
    justifyContent: 'center',
  },
  categoryText: {
    color: '#ffffff',
    fontFamily: fontFamily.gothamBold,
    fontSize: 14,
  },
  categoryTextActive: {
    color: '#06A09A',
    fontFamily: fontFamily.gothamBold,
    fontSize: 14,
  },
  container: {
    backgroundColor: colors.primaryBgColor,
    flex: 1,
  },
  developmentModeText: {
    color: 'rgba(0,0,0,0.4)',
    fontSize: 14,
    lineHeight: 19,
    marginBottom: 20,
    textAlign: 'center',
  },
  dividerContainer: {
    height: 1,
    width: 25,
  },
  dividerContainerEvent: {
    height: 6,
    width: 1,
  },
  dividerContainerRecommended: {
    height: 1,
    width: 0,
  },
  eventItem: {
    alignSelf: 'stretch',
    backgroundColor: '#c1c1c1',
    height: 40,
    marginTop: 3,
    padding: 10,
    textAlign: 'center',
  },
  filterContainer: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: '#EAEAEA',
    borderRadius: 5,
    color: '#707070',
    flex: 9,
    flexDirection: 'row',
    fontFamily: fontFamily.gothamMedium,
    fontSize: 15,
    justifyContent: 'center',
    marginBottom: 30,
    padding: 10,
    paddingLeft: 20,
    paddingRight: 20,
  },
  filterContainerSearch: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: '#EAEAEA',
    borderRadius: 5,
    color: '#707070',
    flex: 1,
    flexDirection: 'row',
    fontFamily: fontFamily.gothamMedium,
    fontSize: 15,
    justifyContent: 'center',
    marginBottom: 30,
    marginLeft: 10,
    padding: 10,
    paddingLeft: 20,
    paddingRight: 20,
  },
  input: {
    alignSelf: 'stretch',
    borderColor: '#7a42f4',
    borderWidth: 1,
    height: 40,
    margin: 15,
    textAlign: 'center',
  },
  searchInput: {
    alignContent: 'flex-start',
    alignItems: 'flex-start',
    alignSelf: 'stretch',
    backgroundColor: '#EAEAEA',
    borderRadius: 5,
    color: '#707070',
    fontFamily: fontFamily.gothamMedium,
    fontSize: 15,
    marginBottom: 30,
    padding: 10,
    paddingLeft: 20,
    paddingRight: 20,
    textAlign: 'left',
  },
});

export default styles;
