export default [
  {
    LanguageCode: null,
    Id: 67,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Paddle Tennis',
    DescriptionInPrimaryLang: 'Paddle Tennis',
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554137560/dxb/icyfptnzl56bco0ivp0c.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554137559/dxb/dvc0zrrnfgaorhu5lwdl.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554137558/dxb/iorlyzkqfcbxtn5quxpv.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554137557/dxb/cw1pfuchc0g6bw4hkunn.png',
    Created: '2019-03-07T11:50:46.567',
    Modified: '2019-03-10T11:26:12.63',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 66,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Cycling',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138251/dxb/yqbhwazoqw8sa4wyf9bh.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138250/dxb/endtnnsudfczjr2anuln.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138249/dxb/enwybqfxhhecuuwtmnp8.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554138248/dxb/zzoovzpueotetmllizfe.png',
    Created: '2019-02-26T10:37:18.94',
    Modified: '2019-02-26T10:37:18.94',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 65,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Power lifting',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138595/dxb/tybzq46z3doojzgfw92r.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138594/dxb/idxc4ndbtknlbwo34lrs.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138593/dxb/olmhunryf8nvnmpoxvkl.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554138592/dxb/n28mvbyshcqprkqqkqp6.png',
    Created: '2019-02-20T15:36:47.137',
    Modified: '2019-02-20T15:36:47.137',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 64,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Ironman',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138603/dxb/vhsi3g58zfeloiwyz02w.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138602/dxb/tpdnonp0dz9t7subytxi.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138601/dxb/ergapn19u0mjxl63j50n.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554138600/dxb/gstpupbstizmgsnxc4rb.png',
    Created: '2019-02-20T15:24:06.64',
    Modified: '2019-02-20T15:24:06.64',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 63,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'UFC',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138610/dxb/gwjd2aqskfokgcs93jmd.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138609/dxb/tfkomflaae0nph96fu2m.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138608/dxb/yyxul0aaqie1lkgxguws.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554138608/dxb/qktmrszsdgiihk4m2uku.png',
    Created: '2019-02-20T15:20:11.897',
    Modified: '2019-02-20T15:20:11.897',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 62,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'MMA',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138618/dxb/ylofub6hgwfyzydn6hq2.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138616/dxb/biscylbif8fvuzdloiio.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138616/dxb/w9ikgsczq9wmayokwony.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554138615/dxb/bouzhhrbc88p21ygpl85.png',
    Created: '2019-02-20T15:02:33.387',
    Modified: '2019-02-20T15:02:33.387',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 61,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Boxing',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138627/dxb/syv8ggsi9siyuo6idh5g.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138626/dxb/kzt78mhbepovxkhqkyg0.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138621/dxb/ygiudj9wxo6wfimfwxag.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554138620/dxb/atjquljgqvapkor3jjbl.png',
    Created: '2019-02-20T14:45:59.13',
    Modified: '2019-02-20T14:47:17.37',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 60,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Jiu-Jitsu',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138638/dxb/gzl1k2xrv4rxck5wp3dm.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138637/dxb/yjeoj5d78wru2cc9e9cd.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138636/dxb/uhuzxpkjvreh13may93p.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554138635/dxb/cc3bojsz5sjhtymwj5jm.png',
    Created: '2019-02-20T14:36:41.5',
    Modified: '2019-02-20T14:36:41.5',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 59,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Crossfit',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138645/dxb/ir7ssvow5zruar0yhoi1.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138644/dxb/xvswru9a1rjgdt3dvqq2.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138643/dxb/qvazzayf7ezajflh8bkp.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554138642/dxb/jsncim2uoby0cpljxtmv.png',
    Created: '2019-02-20T14:24:35.027',
    Modified: '2019-02-20T14:24:35.027',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 58,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Ice Hockey',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138653/dxb/gs2e8vdlhqgxmbbuehuq.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138651/dxb/oipgddblutfoivajpt2y.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138651/dxb/ohbxrv0npzgtejdvmkjk.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554138650/dxb/q2x8tv0p0fr0rmd9dj6n.png',
    Created: '2019-02-20T14:16:24.333',
    Modified: '2019-02-20T14:16:24.333',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 57,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Freestyle',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138660/dxb/pbovz5109vqaepr6skdb.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138659/dxb/eqqj0ipvbaouzwvh1yqg.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138658/dxb/cufw4ezt5jhawj2dgnxs.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554138657/dxb/hzx9xqwbt8ix0qekkbq6.png',
    Created: '2019-02-20T14:12:33.47',
    Modified: '2019-02-20T14:12:33.47',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 56,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Snowboarding',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138667/dxb/dlkxvk70sgszne8sygtp.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138666/dxb/qq2dgf1jm9bebbh7goru.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138665/dxb/or0jqzdegovctkprkrek.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554138664/dxb/ig45izcyu7bn5barewhy.png',
    Created: '2019-02-20T12:53:35.067',
    Modified: '2019-02-20T12:53:35.067',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 55,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Skiing',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138674/dxb/nxysup2cuw7hddggkomb.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138673/dxb/wjawsnu2tygpaytg4hxp.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138672/dxb/cynwe4byz7irvlaks9j2.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554138671/dxb/uljdfpgfrv8pwqxwdnfa.png',
    Created: '2019-02-20T12:50:23.45',
    Modified: '2019-02-20T12:50:23.45',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 54,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Conference',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138681/dxb/gqvhwppwuniyseovkk7u.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138680/dxb/anasfzhxdj4tfmhqwwb0.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138680/dxb/c6vjchj1nimb6kdqaqbe.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554138679/dxb/xaw9mv2tqhoc202rs8tl.png',
    Created: '2019-02-20T12:45:14.35',
    Modified: '2019-02-20T12:45:14.35',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 53,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Chess',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138695/dxb/f4yejmio87itlzodgf2g.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138694/dxb/qicrsp0xru07ui699uul.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138690/dxb/ued7b7zoadoe0fowxmkb.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554138689/dxb/rzmjsqvebniqdvpt7la2.png',
    Created: '2019-02-20T12:26:02.837',
    Modified: '2019-02-20T12:27:32.73',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 52,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Squash',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138631/dxb/pye1m4ainqi5zp8hopjc.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138629/dxb/jx674yih6mpcxmokzpeb.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138629/dxb/x8kjyft2s5ohaeo5ppgu.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554138628/dxb/tvjudh21jljuld9n6oy9.png',
    Created: '2019-02-20T12:13:02.743',
    Modified: '2019-02-20T14:41:19.587',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 51,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Table Tennis',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138715/dxb/auopmczxisu2mhnpspc4.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138714/dxb/x3ldke8w4nfebj3jutgc.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138713/dxb/tqjolniexotaz1ytlyrd.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554138712/dxb/p3akxgt8fsxj4xzsyswl.png',
    Created: '2019-02-20T12:06:14.047',
    Modified: '2019-02-20T12:06:14.047',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 50,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Badminton',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138718/dxb/hxrgx8xkomsnk2ypvazu.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138717/dxb/nhjxk5pu4njj0iiw5spi.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138717/dxb/mscvirk9s6il4bpmvoxa.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554138716/dxb/ad8vhn4yqgvjfvbdkfpl.png',
    Created: '2019-02-20T12:00:02.217',
    Modified: '2019-02-20T12:00:31.043',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 49,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Tennis',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138729/dxb/xpayb59keo79pqgfpgvi.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138728/dxb/uvklg8y0duyupqtuz6ki.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138727/dxb/zns7vfcmvrhejqepsaol.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554138726/dxb/jdw0yomucmuyhlmeyauf.png',
    Created: '2019-02-20T11:39:01.607',
    Modified: '2019-02-20T11:39:01.607',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 48,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Spartan',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138737/dxb/hmutnqcts7hwq5htyw3g.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138736/dxb/qoflwnltaswhgfwooian.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138734/dxb/cpr1gzhz18fcixa4c3fw.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554138734/dxb/upb9v09dauntetuviyc6.png',
    Created: '2019-02-20T11:31:39.54',
    Modified: '2019-02-20T11:31:39.54',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 47,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Desert Warrior',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138743/dxb/pxaaal2kqe4elsybhxvp.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138743/dxb/nyc1gefzsjxh5nzieaxx.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138742/dxb/ufubklajqbav46aditai.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554138741/dxb/zxuxzqfqeryi4fmz7xbf.png',
    Created: '2019-02-20T11:23:26.22',
    Modified: '2019-02-20T11:23:26.22',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 46,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Climbing',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138750/dxb/kdwkpinqsxwdudrkn6ld.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138750/dxb/kcwmpqavvf90coxrvput.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138748/dxb/mppjuxmxd3qiurbtvsu8.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554138748/dxb/ceze5oxkopmitap9noo4.png',
    Created: '2019-02-20T11:14:07.977',
    Modified: '2019-02-20T11:14:07.977',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 45,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Diving',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138759/dxb/qiw70sknlzfhuhcr21eq.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138757/dxb/ky0pg3opibr0pemj5uuq.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138756/dxb/bxvzikz567ytlyoxrqdi.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554138755/dxb/vryokmhyvpnaqublzq5j.png',
    Created: '2019-02-20T11:07:04.087',
    Modified: '2019-02-20T11:07:31.017',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 44,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Sailing',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138767/dxb/vsyxmlommtbg0elgzzei.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138766/dxb/ukabjqol4yltp89gwulv.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138761/dxb/kpgi4ujjlsp5u9ml3hel.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554138760/dxb/kgsygeovdg8itunkvjh8.png',
    Created: '2019-02-20T11:02:37.567',
    Modified: '2019-02-20T11:02:37.567',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 43,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Surfing',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138775/dxb/dgoxkw7qsjjrbkqmswlp.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138774/dxb/gxldxob4tbv5gkmrcnj5.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138769/dxb/wzs3laajpt7fjdca3lu7.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554138768/dxb/tpq6xm3eu2evlbr4qdd8.png',
    Created: '2019-02-20T10:56:51.107',
    Modified: '2019-02-20T10:56:51.107',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 42,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Kitesurf',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138787/dxb/loydyb4plsxe3dh0xceq.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138786/dxb/prcqomx0wpcbgszhycrz.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138785/dxb/wkefwxnzl6zr9rxq5abv.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554138784/dxb/eabcelh2mjkssy9qzs58.png',
    Created: '2019-02-20T10:47:18.893',
    Modified: '2019-02-20T10:47:18.893',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 41,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Kayaking',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138798/dxb/ggsap3frsu5qpjs1mhow.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138797/dxb/zlnbdgiayk3prf93pzzg.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138796/dxb/pxee0ibullch03vgudsq.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554138795/dxb/aqsbfljgrwca6pjyzqkz.png',
    Created: '2019-02-20T10:38:58.107',
    Modified: '2019-02-20T10:38:58.107',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 40,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Canoeing',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138806/dxb/jbdo3s1q5dt8x5hsg173.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138805/dxb/s7bmkl7p9reayt6hh08r.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138804/dxb/wijiwadqmyghsobat8wh.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554138803/dxb/yzrpi5nwyxdlzodp2ql7.png',
    Created: '2019-02-20T10:36:45.537',
    Modified: '2019-02-20T10:36:45.537',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 39,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Paddle',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138815/dxb/kvgyxukg5bcqcuwcd6ge.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138813/dxb/yjhahxfeecjpuss35q1g.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138812/dxb/aw6crjefswgptwpwrfyc.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554138811/dxb/dlwk4ivxnquver1j8glz.png',
    Created: '2019-02-20T10:27:24.037',
    Modified: '2019-02-20T10:27:24.037',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 38,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Yoga',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138822/dxb/teuprqkfdrfwkm9zb7gb.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138821/dxb/fe4cljwijrd4ogtednzu.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138820/dxb/u6i0wxkifztwgaymobwe.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554138819/dxb/ewp8ivbmaugedqjvwlhn.png',
    Created: '2019-02-20T10:21:16.247',
    Modified: '2019-02-20T10:21:16.247',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 37,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Relay',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138830/dxb/d3knpy2rfepadbpt2wtu.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138829/dxb/ypqru1li35qwrmpp5blc.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138828/dxb/s8eardgm0cgbgoowxftr.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554138827/dxb/wcyzuozekru0it8prgyb.png',
    Created: '2019-02-20T10:15:14.58',
    Modified: '2019-02-20T10:15:14.58',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 36,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Marathon',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138844/dxb/wajl26sgwbqbmm0hditc.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138842/dxb/wqxqmcdgvoq2wqjra65m.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138842/dxb/r9rojs24bh2qjutmkaay.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554138841/dxb/csuqnjoseogupnkevca3.png',
    Created: '2019-02-20T09:55:05.453',
    Modified: '2019-02-20T09:55:05.453',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 35,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Horse Racing',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138850/dxb/cuus9obfaeeoym9hcmff.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138849/dxb/hot6qmlqlflnusi7yw9i.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138848/dxb/dfflk5lxqb651u3b9oyb.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554138847/dxb/i5idbwtcnj8nzz5deupo.png',
    Created: '2019-02-20T09:43:52.647',
    Modified: '2019-02-20T09:45:51.473',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 34,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Polo',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138860/dxb/w0kt7qjtzdnp18llbrqx.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138858/dxb/nlwldv9ze54m7ayzn618.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554138857/dxb/jqywy39fch6eab0lyfps.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554138855/dxb/dvu30gaiixslscc61wxd.png',
    Created: '2019-02-20T09:37:24.087',
    Modified: '2019-02-20T09:37:24.087',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 32,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Triathlon',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139109/dxb/t0vcqdai8dwzqfnpvopw.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139108/dxb/hw3usni1hsugrgry4gru.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139107/dxb/yql6g4mzdvg8bbre7exb.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554139106/dxb/dd3dkmdtxyxpracg8xys.png',
    Created: '2019-02-11T20:25:04.69',
    Modified: '2019-02-18T10:44:37.11',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 31,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Golf',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139116/dxb/smmuiskarhghootebhmv.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139115/dxb/m5yqlfte1iec1kuddh93.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139114/dxb/iuyt1d3pegspbobt8zyt.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554139113/dxb/jkjab0tbxy9pdgujjzop.png',
    Created: '2019-02-11T20:19:43.707',
    Modified: '2019-02-18T10:44:04.113',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 30,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Sports Awards',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139123/dxb/c91xngj7uuuyzc6wxwzt.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139121/dxb/ispumow5bctmsm85vddt.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139121/dxb/d8i8l1qfg49rh9cvc0vo.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554139120/dxb/msrjuqi2brp3gbqk0lpd.png',
    Created: '2019-02-11T20:16:23.937',
    Modified: '2019-02-18T10:43:29.97',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 29,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Shooting',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139140/dxb/w1vramnqogena2wbpdca.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139139/dxb/entbo5rsk5lafykmsnin.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139136/dxb/ne1zvugiiq7veznwtasn.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554139135/dxb/kxeeb4gmleidklx9wpew.png',
    Created: '2019-02-11T20:13:36.463',
    Modified: '2019-02-18T10:43:01.357',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 28,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Falconry',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139150/dxb/ux6go76qor1pkaqp6mih.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139149/dxb/chdfi4jsjjbgdr2cadtx.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139146/dxb/izcfhpwz14dzbq3jp8jx.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554139145/dxb/ulwpjg9k0oe6cecmr0sn.png',
    Created: '2019-02-11T20:10:04.667',
    Modified: '2019-02-18T10:42:30.367',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 27,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Fishing',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139160/dxb/lgsx1sas2hfdvygpbpdw.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139158/dxb/vmrsa90oam5tjnld2vsh.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139158/dxb/bag0rrafbaphtieiwmp2.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554139157/dxb/y2leytnmnw3ni4xsgojt.png',
    Created: '2019-02-11T20:07:31.613',
    Modified: '2019-02-18T10:42:05.017',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 26,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Camel Racing',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139177/dxb/giao2eqvpnkpc5dnwmle.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139176/dxb/aefzzmbj8h186dmqxa69.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139175/dxb/mzux4vosjc4k5tbv42rx.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554139174/dxb/lcjinnixgddwbht4u1wa.png',
    Created: '2019-02-11T19:51:26.457',
    Modified: '2019-02-18T10:40:17.987',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 25,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Strongman',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139189/dxb/vqzavverndxflktpvprr.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139188/dxb/wj1a7yq0xwqn87nvcglu.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139187/dxb/na5r6aacs5xb0b3giwzi.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554139186/dxb/ctxdudh6etw7mmqqhjuc.png',
    Created: '2019-02-11T19:49:10.607',
    Modified: '2019-02-18T10:39:45.367',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 24,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Darts',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139196/dxb/obggm2s7pc26u7urb5iv.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139195/dxb/nrm7zwpg1l3snlukbujn.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139194/dxb/jsnelbvtuw10badmxvt6.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554139193/dxb/axgeofgf0pzeuzpkliv6.png',
    Created: '2019-02-11T19:47:02.667',
    Modified: '2019-02-18T10:37:18.803',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 23,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Archery',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139200/dxb/ysi2jcsqmdabix8p2qjr.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139199/dxb/qxkjillfq09in4jaf0xi.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139198/dxb/vodyxhgtb9rbblfazrqm.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554139197/dxb/uybjzemtywymgyjykjcp.png',
    Created: '2019-02-11T19:42:31.213',
    Modified: '2019-02-18T10:36:40.763',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 22,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Motorsport',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139212/dxb/wrmkncldpfuudkoaj4dp.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139211/dxb/vjiddkjngh7rwqrocfyg.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139210/dxb/fvc3ajk9c30j6csqv9wl.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554139209/dxb/g9zppeli5ssy44lgg2rv.png',
    Created: '2019-02-11T19:25:21.053',
    Modified: '2019-02-18T10:36:07.66',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 21,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Combat sports',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139224/dxb/dyvynk7vcfxl3zhhhegx.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139223/dxb/ezcjbk5a9ye2gj2e5dwh.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139222/dxb/mhzwluppwpael0vardpv.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554139221/dxb/bjupmoltwx3nb9bbn80f.png',
    Created: '2019-02-11T19:21:05.043',
    Modified: '2019-02-18T10:35:24.263',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 20,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Multisport',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139232/dxb/p1eohhabemac2dq1ovpy.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139231/dxb/flceeswmeo8olzwxsrrq.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139230/dxb/oxek5kvk7nspghntlp8a.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554139229/dxb/jrgirljbl7pz2jbfopdv.png',
    Created: '2019-02-11T19:16:34.783',
    Modified: '2019-02-18T10:34:52.543',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 19,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Winter sports ',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139239/dxb/itylg8daxperpiuudpkc.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139238/dxb/mpnjzcmiglh4yubmdhp0.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139237/dxb/clii4oidsvpnmxspa3za.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554139237/dxb/sq85o7ecvyafel7yngmz.png',
    Created: '2019-02-11T19:08:55.58',
    Modified: '2019-02-18T10:31:05.08',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 18,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Basketball',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139373/dxb/uxx2hwfcvbh3tcyl6hqq.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139372/dxb/mkmak3ag1jvhrvfadm0u.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139367/dxb/dbdykmfnlehdjwjdaxs0.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554139366/dxb/bzsfhahflhyfc5fi72pb.png',
    Created: '2019-02-11T15:18:55.677',
    Modified: '2019-02-18T10:30:36.283',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 17,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Volleyball',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139380/dxb/c9mf7scgw7ukzuuyspwq.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139379/dxb/j1t85jbuknhxfjuofdep.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139374/dxb/uq8lso1brb1eu5dcqkv8.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554139373/dxb/vm8kxqycevyzqoewh1ty.png',
    Created: '2019-02-11T15:13:14.143',
    Modified: '2019-02-18T10:29:36.69',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 16,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Other',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139389/dxb/bwoh8iotx6afcbjkxwby.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139388/dxb/cf4dicg9ytlak4gtnsi5.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139387/dxb/qqo7lvjtqt5xcanrkjyc.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554139385/dxb/y5enkqefteow7xohndci.png',
    Created: '2019-02-11T15:10:31.793',
    Modified: '2019-02-18T10:29:08.307',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 15,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Para Sport',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139406/dxb/a8ufdsokpu8lcsdl8y4w.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139405/dxb/q7wnfdfcnjmxwt5awgmr.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139403/dxb/tytr9j6vk6ggwmtkbl8q.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554139403/dxb/n23xs1hxg6abmkjjgdyg.png',
    Created: '2019-02-11T15:07:37.08',
    Modified: '2019-02-18T10:28:30.59',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 14,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Racquet sports ',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139413/dxb/mhxshgs9j7ffj7gnfpjz.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139412/dxb/nih4burrzyftco9davar.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139411/dxb/xfmndngczkn0djzpo4p3.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554139410/dxb/wtdgetq4g9hwdtz3kusk.png',
    Created: '2019-02-11T15:03:51.003',
    Modified: '2019-02-18T10:28:05.1',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 13,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Adventure sports ',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139425/dxb/fwifvtmvf39wdrezplud.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139424/dxb/j4tmgggtafmsfwqfkcad.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139421/dxb/dvtnbtqliedhtklk5jat.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554139420/dxb/jsjnpce5ic5gdlotv9gk.png',
    Created: '2019-02-11T15:00:31.16',
    Modified: '2019-02-18T10:27:39.93',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 12,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Watersports',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139438/dxb/nbx3o9ljlgwbmdvt5g7j.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139437/dxb/idm0zy1sefe2djlid1oi.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139434/dxb/gobucqfgbk0aic0pkwk5.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554139434/dxb/manysotkrngcc2zfdb01.png',
    Created: '2019-02-11T14:55:50.33',
    Modified: '2019-02-18T10:27:15.66',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 11,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Gymnastics',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139453/dxb/hso45wdumxubvxbegagk.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139452/dxb/pvursq2klm93ankcc8o1.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139451/dxb/te0xg8mo96243kdfqco3.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554139450/dxb/yxl5qupht9hzhsdowmmc.png',
    Created: '2019-02-11T14:50:29.353',
    Modified: '2019-02-18T10:26:26.173',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 10,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Athletics ',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139459/dxb/ze6m3dx4mra5a9gxkead.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139459/dxb/iknfddry4hhljxipr6dd.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139458/dxb/ttfv38ayzslpf7osstwn.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554139457/dxb/u2o7fo7cfgvy5nrv857s.png',
    Created: '2019-02-11T14:42:52.433',
    Modified: '2019-02-18T10:25:23.93',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 9,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Equine sports',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139467/dxb/mznsptwxfvimdmv2oesd.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139465/dxb/cl8z9daahhujm3nbquy0.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139465/dxb/lt57cu4bglpz4jufzqt8.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554139464/dxb/dnqqwhukzen5ruv6o0fz.png',
    Created: '2019-02-11T14:35:23.607',
    Modified: '2019-02-18T10:24:38.867',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 8,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Rugby',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139474/dxb/bjk3khmbf4yswvkr507v.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139473/dxb/ggy8c1cal4ebw1i9uzmq.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554139472/dxb/hgg9cyxyxx8od36sh1uk.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554139471/dxb/zagdpkjlndkxjkvdyvmv.png',
    Created: '2019-02-11T14:20:26.337',
    Modified: '2019-02-18T10:23:02.677',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 6,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Swimming',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554140864/dxb/aih7rwe6mjimwkwzwpem.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554140863/dxb/ocxlsllkr7civqi2wl2c.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554140862/dxb/vkqproewcu30cmlstyca.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554140861/dxb/raflysoyipsux0t1kqwt.png',
    Created: '2018-12-03T15:22:07.317',
    Modified: '2019-02-18T10:46:18.087',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 4,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Running',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554140856/dxb/iiws2bxevjzetcagqicz.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554140855/dxb/sfkxgc4ffcexsaf2oybt.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554140855/dxb/ygo8mnua4yyrxfsk21hr.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554140854/dxb/kisbnvnghprodrv5daaw.png',
    Created: '2018-12-03T12:27:34.513',
    Modified: '2019-02-18T10:45:21.857',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 3,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Football',
    DescriptionInPrimaryLang: 'Football',
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554140870/dxb/swggygyinsu5zbaq0m1v.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554140869/dxb/w8ccffkhxlz14ctzqg84.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1556022165/dxb/dsfre8cvlnyotqeqsjh2.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1556022170/dxb/isl4a3n8yv6dactd9jcy.png',
    Created: '2018-11-05T17:06:41.373',
    Modified: '2019-04-23T12:22:55.837',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  },
  {
    LanguageCode: null,
    Id: 2,
    EncId: null,
    ParentCategoryId: 0,
    NameInPrimaryLang: 'Cricket',
    DescriptionInPrimaryLang: null,
    ImageURL: null,
    ImageThumbURL: null,
    ImageSquareURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554140867/dxb/iketsre6eti9e30ylmba.png',
    ImageSquareThumbURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554140866/dxb/tlel5tkc0d4akxq5zovz.png',
    ImageLandscapeURL: 'https://res.cloudinary.com/sports-gate/image/upload/v1554140865/dxb/rlluqhq6btuysqrto50f.png',
    ImageLandscapeThumbURL:
      'https://res.cloudinary.com/sports-gate/image/upload/v1554140865/dxb/xlufawsf3odzxum1qjx3.png',
    Created: '2018-10-10T14:59:08.503',
    Modified: '2019-02-18T10:47:02.413',
    IsActive: true,
    IsFeatured: false,
    IsDeleted: false,
    MetaName: null,
    MetaDesc: null,
    MetaKeywords: null,
    MetaAuthor: null,
    MetaCopyright: null
  }
]
