export default [
  {
    TicketCode: '',
    PaymentDate: '',
    PricingCategoryName: 'Ticketed Event',
    SectorName: '',
    Row: 'A',
    Seat: '44',
    Count: 1,
    Price: 234.12,
    EventId: 123,
    EventName: 'Hello Kitty Run',
    EventStartDate: '13 Dec 2019',
    VenueId: 412,
    VenueName: 'Hamdam Sports Complex',
    VenueFullAddress: '',
    FacilityId: 51,
    FacilityName: '',
  },
  {
    TicketCode: '',
    PaymentDate: '',
    PricingCategoryName: 'Ticketed Event',
    SectorName: '',
    Row: 'A',
    Seat: '44',
    Count: 1,
    Price: 234.12,
    EventId: 123,
    EventName: 'Hello Kitty Run',
    EventStartDate: '13 Dec 2019',
    VenueId: 412,
    VenueName: 'Hamdam Sports Complex',
    VenueFullAddress: '',
    FacilityId: 51,
    FacilityName: '',
  },
  {
    TicketCode: '',
    PaymentDate: '',
    PricingCategoryName: 'Ticketed Event',
    SectorName: '',
    Row: 'A',
    Seat: '44',
    Count: 1,
    Price: 234.12,
    EventId: 123,
    EventName: 'Hello Kitty Run',
    EventStartDate: '13 Dec 2019',
    VenueId: 412,
    VenueName: 'Hamdam Sports Complex',
    VenueFullAddress: '',
    FacilityId: 51,
    FacilityName: '',
  },
];
